### ISSUE TITLE
Tap don't work in 'add skill dropdown'. Only clicks are working.

### ISSUE THREAD

**Issue by yfer** [DevvJobs/candidates-web#136]
On latest windows/chrome.

**Comment by ivan-kolmychek-devv** [comment]
@yfer thanks for the report, we'll look into it.

**Comment by ivan-kolmychek-devv** [comment]
@yfer just to clarify - you mean the tap as in `tap` event, via touch-screen, right?

**Comment by yfer** [comment]
@ivan-kolmychek-devv  my bad, tap on touchpad.

**Comment by ivan-kolmychek-devv** [comment]
@yfer that's weird, I always assumed they just emulate click.

According to [this article](https://www.howtogeek.com/370238/how-to-use-touchpad-gestures-for-windows-10/)

> Tap one finger on the touchpad: Select an item (same as left-clicking a mouse).

Can you please try to confirm it? The steps are:
- open the Chrome
- open any page (just new tab works as well)
- open developers console (by pressing `F12` on Windows usually)
- past this code (to catch and note clicks to console) and press `Enter`:
```js
document.querySelector("body").addEventListener("click", function() { 
  console.log("click"); 
})
```
- click anywhere on the page (not in console) and see do clicks get reported to the console

If it doesn't, then we'll have to look more into what exactly event does it emit and right now I don't have any better guess.

**Comment by ivan-kolmychek-devv** [comment]
I'm closing this since it's been 14 days since it was open and we haven't heard back.
If anyone has the same problem, please create a new issue and reference there this one.
