### ISSUE TITLE
Chat: Redirect to `/chat` if contact with id from url was not found (only when there are no contacts)

### ISSUE THREAD

**Issue by tetiana-kolmychek-devv** [DevvJobs/candidates-web#15]
Right now if user mistypes in chat url, page will show loader on the place of messages.
Instead we should redirect to `/chat` route.

**Comment by lilsweetcaligula** [comment]
Could you please help me reproduce this issue?

Currently, if I have open the chat page with a path, like this:
/profile/chat/zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz

- mistyping the uuid and pressing the Return key, will redirect me to the chat page and display the chat list. The loader will promptly disappear.

**Comment by tetiana-kolmychek-devv** [comment]
@lilsweetcaligula if you type wrong `id` after `profile/chat/` and don't press any keys, you should see something like this (if you have any contacts, you will not see empty contacts message, just loader)
![screenshot_20190225_111019](https://user-images.githubusercontent.com/23338797/53334430-17463500-38f9-11e9-9c60-93b3e995ee65.png)

My suggestion is to redirect user to `/profile/chat` in case like this right away, without waiting for them to press Return, Back or anything else.

**Comment by lilsweetcaligula** [comment]
Oh, I see now. It only seems to happen when you have no chats at all.

**Comment by tetiana-kolmychek-devv** [comment]
@lilsweetcaligula tested, you are right, I changed title of the issue.

**Comment by ivan-kolmychek-devv** [comment]
The #22 has been deployed to https://dev.devv.jobs now.

**Comment by tetiana-kolmychek-devv** [comment]
Deployed to https://devv.jobs.
