### ISSUE TITLE
Automatic deployment to dev.devv.jobs is broken.

### ISSUE THREAD

**Issue by ivan-kolmychek-devv** [DevvJobs/candidates-web#18]
Due to an overlook during pipeline configuration, auto-deployment of master branch to dev.devv.jobs is broken right now.

I'm looking into how it can be fixed, but until then we'll have to trigger builds manually after PR merges.

I apologize for any inconvenience.

**Comment by ivan-kolmychek-devv** [comment]
Since it's has been almost 24 hours, I think this deserves status update and a bit more details.

We use private Buildkite pipeline to build code from this repo into final bundle and deliver it to to [development](https://dev.devv.jobs) and [live/production](https://devv.jobs) environments. 

[Buildkite has security check turned on by default that prevents builds from being triggered if the email of commit author does not belong to a member of organization](https://buildkite.com/docs/pipelines/trigger-step#permissions), so when we merge community contributions, buildkite refuses to trigger deployment pipeline with message like this one:

> 2019-02-26 08:32:30 ERROR  Unrecoverable error, skipping retries
> 2019-02-26 08:32:30 FATAL  Failed to upload and process pipeline: POST https://agent.buildkite.com/v3/jobs/pipeline-id-here/pipelines: 422 Builds cannot be triggered from this pipeline as there is no Buildkite user linked to this build. Ensure that a user has added "github-committer-email-here" as a verified email address on their account.
> Error: The command exited with status 1 

We cannot disable it on our own.

So we are in contact with Buildkite support about this and they suggested to disable this check for us.
Until this is done we'll have keep to manually trigger builds. :)

**Comment by ivan-kolmychek-devv** [comment]
Buildkite support got back to us and wrote that check has been disabled.

Until we merge any new external contribution we can't say for sure that issue has been resolved, so I'll leave it open until we can.

**Comment by tetiana-kolmychek-devv** [comment]
Can confirm that now deploy us working again.
