### ISSUE TITLE
Add "not found" error page

### ISSUE THREAD

**Issue by tetiana-kolmychek-devv** [DevvJobs/candidates-web#3]
At the moment we don't have page where user would be routed when url does not exist.
We should add one and make sure users get redirected there when appropriate.

**Comment by Yusadolat** [comment]
Hey @tetiana-kolmychek-devv I wanna work on this issue, Can I ?

**Comment by DevvKris** [comment]
Feel free! // Kris

**Comment by tetiana-kolmychek-devv** [comment]
Deployed to development, after testing and deploy to production this issue can be closed.

Url for testing on development version: https://dev.devv.jobs

**Comment by tetiana-kolmychek-devv** [comment]
Deployed to https://devv.jobs.
