### ISSUE TITLE
Add link to repository in UI for logged in people?

### ISSUE THREAD

**Issue by ivan-kolmychek-devv** [DevvJobs/candidates-web#30]
#25 talks about adding link to repo to landing page, but then you would have to be logged out to see it.

How should it look and where should it be? Suggestions are welcome. :slightly_smiling_face:

**Comment by tetiana-kolmychek-devv** [comment]
I would suggest to place it in the sidebar, mb near logout link.

**Comment by lilsweetcaligula** [comment]
Maybe append a footer to the page, and place the repo link in the footer, potentially along with other contact and legal info?

**Comment by ivan-kolmychek-devv** [comment]
Both sound good to me, but I am not that good with graphical/UI design. @tetiana-kolmychek-devv @DevvKris what do you think?

**Comment by tetiana-kolmychek-devv** [comment]
@lilsweetcaligula 

If we place it in footer, we need to add one. It has to either be static or not. I think that neither work good for us.

If we take static one, it is hard to find a place for it - we already have a lot of static parts like sidebar, especially in the chat section. We could place it in profile part, but then it looses quite a lot of visibility. 

If we take a non-static one, it may work for some pages, like profile, but it will not work for other, like chat. So we are again stuck with it being on few pages only, as result it looses a lot of visibility.

Sidebar is already static and visible (almost) on every page. So if we want people to actually notice the link, I think that is the best place where to put it. :)

**Comment by ivan-kolmychek-devv** [comment]
Picked it up.

**Comment by ivan-kolmychek-devv** [comment]
Deployed to https://dev.devv.jobs.

**Comment by ivan-kolmychek-devv** [comment]
Deployed to https://devv.jobs. Closing as done.
