### ISSUE TITLE
Add a separate page for signup (/sign/up)

### ISSUE THREAD

**Issue by ivan-kolmychek-devv** [DevvJobs/candidates-web#36]
It should contain the form that is right now on the landing page and should be located at `/sign/up`.

It can be similar to sign in page that we have right now at `/sign/in`.

Extracted from #25, for more context you can see [this comment](https://github.com/DevvJobs/candidates-web/issues/25#issuecomment-474256164).

Feedback and suggestions are welcome.

**Comment by tetiana-kolmychek-devv** [comment]
A bit more additional info:
- when creating this page, we should change link `Create account` on page `/sign/in` to point to new page (Just to not forget to change it later when landing will be redesigned :) ) 
- form error handling and redirect after success should be the same as for current sign up form (I think it can be just copied)
- style for desktop and mobile view can be taken from `sign/in` page
- page should have same links to terms and privacy policy as form on the index page right now (I think it can be just copied)

**Comment by ivan-kolmychek-devv** [comment]
Deployed to https://devv.jobs.
