### ISSUE TITLE
Chat: add search by company name/representative name

### ISSUE THREAD

**Issue by tetiana-kolmychek-devv** [DevvJobs/candidates-web#4]
There is a styled commented section in ChatNavigation component that was not implemented.
We should add functionality to commented element to search by company name or representative name.
Search should happened only in active tab and be "on the go" - without user pressing any buttons to submit form.

(For the example of similar functionality you can check how search is implemented in tests)

**Comment by tetiana-kolmychek-devv** [comment]
Deployed to development version, needs testing from actual mobile interfaces, not browser simulation.
Link for testing: https://dev.devv.jobs

**Comment by tetiana-kolmychek-devv** [comment]
I confirmed that it works for desktop, but not for the mobile phones.
For mobile chat changes need to be propagated to `ChatThreads` component.

@lilsweetcaligula would you like to do that or should I create a separate issue?

**Comment by lilsweetcaligula** [comment]
@tetiana-kolmychek-devv Could you create a separate issue please? Then it can be picked up by whoever is available at the time. If I have the time, I'll look into it.
