### ISSUE TITLE
Replace auth endpoints with new graphql endpoint and mutations

### ISSUE THREAD

**Issue by tetiana-kolmychek-devv** [DevvJobs/candidates-web#41]
We decided to move our only non-gql endpoints to gql as well and prepared structure for it on API already. (url if you want to test API in Altair: `https://stage.devvapi.com/candidates/v1/auth/graphql`)

Now we will replace them on the frontend. I will not remove old components and services right away, leaving them for around a month.
After implementation we plan to test it for a few days on the development version before propagating to the production.

**Comment by ivan-kolmychek-devv** [comment]
Deployed to https://devv.jobs.
