### ISSUE TITLE
Remove sf font

### ISSUE THREAD

**Issue by tetiana-kolmychek-devv** [DevvJobs/candidates-web#46]
We discovered that one of our fonts have licence, prohibiting us from using it, so we should remove it and mb later create issue to find new font with proper licence if current replacement (Arial) would not be good enough.

**Comment by nocategory** [comment]
When the redesign is implemented, the landing page font will be changed to Montserrat, according to the already shared designs

**Comment by ivan-kolmychek-devv** [comment]
Deployed to https://devv.jobs.
